language: go
go:
    - 1.4

script:
    - make install
    - make generate
    - cd $HOME/gopath/src/github.com/eliothedeman/bangarang; export GOPATH=$(pwd):$(pwd)/vendor; go test -p=1 github.com/eliothedeman/bangarang/...
